# ITCR - Sede Interuniversitaria de Alajuela
# Curso IC-6200 - Inteligencia Artificial


### Algebra lineal, vectores y matrices (utilizando Pytorch) 
### Tarea

### Profesora: María Mora


Medio de entrega: Por medio del TEC-Digital.

Entregables: Un archivo en jupyter (.ipynb) y archivo de imagen empacados en un archivo .zip. 

Modo de trabajo: en grupos de máximo dos personas.

Integrantes 

Rodolfo Cruz Vega - 2013235955

Jonathan Quesada Salas - 2020023583

---

Objetivo: experimentar con conceptos elementales respecto a matrices para reforzar el conocimiento adquirido durante el estudio del material.

Lenguaje a utilizar: Python con la librería Pytorch. Utilice en TODOS los ejercicios tensores de Pytorch para que cuando estos sean utilizados en aprendizaje profundo sean más fluidas las explicaciones y ejercicios. 

---


**Pregunta 1 (10 puntos)**

Considerando que la transpuesta de una matriz es el resultado de cambiar las filas a columnas. Sea una matriz $A\in\mathbb{R}^{m\times n}$, su transpuesta se escribe como $A^{T}\in\mathbb{R}^{n\times m}$ y sus entradas están dadas por: 

\begin{equation}
\left(A^{T}\right)_{i,j}=A_{j,i}.
\end{equation}

Las siguientes son propiedades de la transpuesta: 

- $\left(A^{T}\right)^{T}=A$
- $\left(AB\right)^{T}=B^{T}A^{T}$
- $\left(A+B\right)^{T}=A^{T}+B^{T}$.



---



Utilizando pytorch, genere dos matrices con datos aleatorios de dimensiones $A\in\mathbb{R}^{4\times 3}$   y  $B\in\mathbb{R}^{3\times 4}$  y muestre que la siguiente propiedad se cumple con las matrices propuestas.

$\left(AB\right)^{T}=B^{T}A^{T}$

**Nota:**. Para la demostración debe crear una función (con retorno falso o verdadero) que reciba una matriz y verifique que las igualdades se cumplen (5 puntos). Su función debe recibir **matrices de cualquier tamaño** y verificar que es posible realizar los cálculos requeridos con ellas (5 puntos). 




In [ ]:
import torch

A = torch.rand((4, 3))

B = torch.rand((3, 4))

AB_transpose = torch.matmul(A, B).T


def demostrar_propiedad(A, B):
    """
    Función para demostrar la propiedad (AB)^T = B^T A^T para cualquier matriz A y B de dimensiones compatibles.
    
   """
    
    # Verificamos dimensiones 
    if A.shape[1] != B.shape[0]:
        print("Las dimensiones de las matrices no son diferentes.")
        return False
    else:
        # multiplicación de matrices y  transpuesta
        AB_transpose = torch.matmul(A, B).T
        BT_AT = torch.matmul(B.T, A.T)

        # Comparamos los resultados
        if torch.allclose(AB_transpose, BT_AT):
            return True
        else:
            return False

print(A)
print(B)
print(AB_transpose)

print("prueba de propiedad de transpuesta: ", demostrar_propiedad(A, B))            

tensor([[0.2224, 0.6026, 0.2191],
        [0.7637, 0.1933, 0.0069],
        [0.5842, 0.8492, 0.3653],
        [0.7351, 0.2861, 0.8157]])
tensor([[0.7441, 0.9698, 0.0687, 0.1000],
        [0.0916, 0.0585, 0.8917, 0.5045],
        [0.8097, 0.3896, 0.1338, 0.8832]])
tensor([[0.3981, 0.5916, 0.8083, 1.2337],
        [0.3363, 0.7547, 0.7586, 1.0475],
        [0.5819, 0.2258, 0.8462, 0.4147],
        [0.5198, 0.1800, 0.8095, 0.9383]])
prueba de propiedad de transpuesta:  True


**Pregunta 2 (10 puntos, 5 puntos cada ejercicio)**


Un conjunto de vectores $\left\{ \vec{x}_{1},\vec{x}_{2},\ldots,\vec{x}_{n}\right\} \in\mathbb{R}^{m}$ se dice que es linealmente independiente, si ningún vector de tal conjunto puede ser representado como una combinación lineal del resto de vectores. De lo contrario, si uno de los vectores en tal conjunto puede ser representado como una combinación lineal del resto de vectores, entonces los vectores son linealmente dependientes, lo que se expresa como: 

\begin{equation}
\vec{x}_{j}=\sum_{i=1}^{n-1}\alpha_{i}\vec{x}_{i}
\end{equation}

para cualquier conjunto de valores escalares $\alpha_{1},\ldots,\alpha_{n-1}\in\mathbb{R}$ se dice que el vector $\vec{x}_{j}\in\mathbb{R}^{m}$ es linealmente dependiente de los vectores $\vec{x}_{i}$. 



---

**Pregunta 2.1** Proponga una matriz $A\in\mathbb{R}^{5\times 5}$, que no sea la matriz identidad, de manera que dicha matriz sea de rango completo. Muestre con pytorch que cumple esta propiedad.

**Pregunta 2.2** Ahora hágale cambios a su matriz de manera que sea de rango $3$, y luego más cambios para que sea de rango $2$. Muestre cómo va cambiando la matriz y el cálculo del rango en pytorch.

In [ ]:
# Ejercicio 2.1
import torch
A = torch.tensor([
    [2, 3, 1, 5, 4],
    [1, 5, 2, 3, 6],
    [4, 1, 3, 2, 5],
    [3, 2, 4, 1, 5],
    [1, 4, 2, 5, 3]
], dtype=torch.float)

print(torch.linalg.matrix_rank(A)) # output: 5

tensor(5)


In [ ]:
# Ejercicio 2.2
import torch

A = torch.tensor([    [2, 3, 1, 5, 4],
    [1, 5, 2, 3, 6],
    [4, 1, 3, 2, 5],
    [3, 2, 4, 1, 5],
    [1, 4, 2, 5, 3]
], dtype=torch.float)

A[1] += A[0]
A[2] += A[0]
A[4] += A[3]

print(A)
print(torch.linalg.matrix_rank(A)) # output: 3

tensor([[ 2.,  3.,  1.,  5.,  4.],
        [ 3.,  8.,  3.,  8., 10.],
        [ 6.,  4.,  4.,  7.,  9.],
        [ 3.,  2.,  4.,  1.,  5.],
        [ 4.,  6.,  6.,  6.,  8.]])
tensor(5)


**Pregunta 3 (5 puntos)**

Pseudo inversa de una matriz. La pseudo inversa es una generalización de una matriz inversa que permite calcular una aproximación a la inversa de una matriz, cuando A no es invertible.

Sean las siguientes propiedades con $A\in\mathbb{R}^{m\times n}$:

1. $ \left(A^{T}A\right)^{-1}A^{T}\approx A^{+} $
2.  $\left(A^{T}A\right)^{+}A^{T}=A^{+}$

Seleccione alguna de las propiedades anteriores, cree una función que reciba una matriz y demuestre que se cumple la propiedad seleccionada. 

Pruebe su función con una matriz invertible y con una no invertible. 

In [ ]:
import torch

def pseudoinverse(A):
    # calculamos (A^T A)+ y A^T
    A_T = torch.transpose(A, 0, 1)
    A_TA = torch.matmul(A_T, A)
    A_TAp = torch.pinverse(A_TA)
    
    # calculamos A+
    Ap = torch.matmul(A_TAp, A_T)
    return Ap

# ejemplo con matriz invertible
A_invertible = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 10]], dtype=torch.float32)
Ap_invertible = pseudoinverse(A_invertible)
print("Matriz invertible A:\n", A_invertible)
print("Pseudo-inversa de A:\n", Ap_invertible)
print("Verificación de propiedad: ", torch.allclose(torch.matmul(Ap_invertible, A_invertible), torch.eye(3), rtol=1e-03, atol=1e-03))

# ejemplo con matriz no invertible
A_no_invertible = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float32)
Ap_no_invertible = pseudoinverse(A_no_invertible)
print("Matriz no invertible A:\n", A_no_invertible)
print("Pseudo-inversa de A:\n", Ap_no_invertible)
print("Verificación de propiedad: ", torch.allclose(torch.matmul(Ap_no_invertible, A_no_invertible), torch.eye(3), rtol=1e-03, atol=1e-03))

Matriz invertible A:
 tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8., 10.]])
Pseudo-inversa de A:
 tensor([[-0.6667, -1.3334,  1.0000],
        [-0.6667,  3.6668, -2.0001],
        [ 1.0000, -2.0000,  1.0000]])
Verificación de propiedad:  True
Matriz no invertible A:
 tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
Pseudo-inversa de A:
 tensor([[-0.0781, -0.0625,  0.0156],
        [-1.2500, -0.3125,  0.6250],
        [ 1.0938,  0.2812, -0.5938]])
Verificación de propiedad:  False


**Pregunta 4 (10 puntos, 5 puntos cada ejercicio)**

Sea $A\in\mathbb{R}^{n\times n}$, realice lo siguiente:

---

**Pregunta 4.1**

Defina la función es_simetrica_o_antisimetrica que reciba una matriz, verifique si esta es cuadrada y despliegue un mensaje indicando si la matriz es simétrica, antisimétrica o ninguna de las anteriores. 

**Pregunta 4.2**

Utilizando la función es_simetrica_o_antisimetrica muestre que la matriz resultante de la operación $A+A^{T}$ es simétrica y la matriz $A-A^{T}$ es anti-simétrica para cualquier matriz $A\in\mathbb{R}^{n\times n}$.


In [ ]:
import torch

A = torch.tensor([
    [2, 3, 1, 5, 4],
    [1, 5, 2, 3, 6],
    [4, 1, 3, 2, 5],
    [3, 2, 4, 1, 5],
    [1, 4, 2, 5, 3]
], dtype=torch.float)

B = torch.tensor([
    [1, 2, 3],
    [2, 4, 5],
    [3, 5, 6]])

C = torch.tensor([
    [0, 3, 9],
    [-3, 0, -5],
    [-9, 5, 0]])

def es_simetrica_o_antisimetrica(A):
    """
    Reciba una matriz, verifique si esta es cuadrada y despliegue un mensaje indicando si la matriz es simétrica, antisimétrica o ninguna de las anteriores
    """
    
    if A.shape[0] != A.shape[1]:
        return "La matriz debe ser cuadrada cuadrada."
    else:
        # Verificamos si la matriz es simétrica o antisimétrica
        if torch.allclose(A, A.T):
            return "Es simétrica."
        elif torch.allclose(A, -A.T):
            return "Es antisimétrica."
        else:
            return "Ni simétrica ni antisimétrica."

print(A)
print(es_simetrica_o_antisimetrica(A))
print(B)
print(es_simetrica_o_antisimetrica(B))
print(C)
print(es_simetrica_o_antisimetrica(C))

tensor([[2., 3., 1., 5., 4.],
        [1., 5., 2., 3., 6.],
        [4., 1., 3., 2., 5.],
        [3., 2., 4., 1., 5.],
        [1., 4., 2., 5., 3.]])
Ni simétrica ni antisimétrica.
tensor([[1, 2, 3],
        [2, 4, 5],
        [3, 5, 6]])
Es simétrica.
tensor([[ 0,  3,  9],
        [-3,  0, -5],
        [-9,  5,  0]])
Es antisimétrica.


In [ ]:
A = torch.rand(3, 3)

B = A + A.T

print(es_simetrica_o_antisimetrica(B))

C = A - A.T

print(es_simetrica_o_antisimetrica(C))

La matriz es simétrica.
La matriz es antisimétrica.
